language: c

# Optional: To use Travis CI's newer container infrastucture,
# un-comment the following line. (Also be sure RACKET_DIR is set to
# somewhere like ~/racket that doesn't require sudo.)
#
# sudo: false

env:
  global:
    # Supply a global RACKET_DIR environment variable. This is where
    # Racket will be installed. A good idea is to use ~/racket because
    # that doesn't require sudo to install and is therefore compatible
    # with Travis CI's newer container infrastructure.
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=5.3.6
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

install:

before_script:

# Here supply steps such as raco make, raco test, etc.
#
# Tip: Use `raco pkg install --deps search-auto <pkg>` to install any
# required packages without getting stuck on a confirmation prompt.
script:
  - raco make "Chapter One/Exercise-1.rkt"
  - raco test -x .

# NOTE: If your repo is a Racket package with an info.rkt that
# includes some `deps`, the following is more elegant:
#
# script:
# - cd ..   # Travis did a cd into the dir. Back up, for the next:
# - raco pkg install --deps search-auto --link <pkg>
# - raco test -x -p <pkg>

after_script:
